spring.application.name=b2bwholesale

spring.datasource.url=jdbc:postgresql://localhost:5432/b2b_db
spring.datasource.username=postgres
spring.datasource.password=PostAP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080